default_stages: [push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.18.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: style-check
        name: style-check
        stages: [commit]
        language: system
        pass_filenames: false
        entry: pipenv run inv style
        types: [python]

      - id: security-check
        name: security-check
        stages: [push]
        language: system
        pass_filenames: false
        entry: pipenv run inv secure
        types: [python]

      - id: test
        name: test
        stages: [commit]
        language: system
        pass_filenames: false
        entry: pipenv run inv test
        types: [python]
