site_name: Wanini's Financial Technical Analysis Library
nav:
    - Home: README.md
    - Contributing: contributing.md

repo_url: https://github.com/Wanini0209/wTA-Lib
remote_branch: gh-pages
remote_name: origin
